@TodoApi_HostAddress = https://localhost:7290

GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "play football",
  "isComplete": false,
  "secret": "yes"
}

###

GET {{TodoApi_HostAddress}}/api/todoitems

###

@id=3
GET {{TodoApi_HostAddress}}/api/todoitems/{{id}}

###

@id=2
PUT {{TodoApi_HostAddress}}/api/todoitems/{{id}}
Content-Type: application/json

{
  "id": 2,
  "name": "play hockey",
  "isComplete": true
}

###

@id=1
DELETE {{TodoApi_HostAddress}}/api/todoitems/{{id}}

###
